// <auto-generated />
using System;
using DeliveryItems;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryItems.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220527133553_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryItems.Models.BagModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BagStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DeliveryPointId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Bags");
                });

            modelBuilder.Entity("DeliveryItems.Models.PackageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedBagId")
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DeliveryPointId")
                        .HasColumnType("uuid");

                    b.Property<int>("PackageStatus")
                        .HasColumnType("integer");

                    b.Property<float>("VolumetricWeight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBagId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("DeliveryItems.Models.PackageModel", b =>
                {
                    b.HasOne("DeliveryItems.Models.BagModel", "AssignedBag")
                        .WithMany("Packages")
                        .HasForeignKey("AssignedBagId");

                    b.Navigation("AssignedBag");
                });

            modelBuilder.Entity("DeliveryItems.Models.BagModel", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
