version: '3.1'

services:

  db:
    container_name: delivery_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - project-network


 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - project-network

  delivery_api:
    container_name: delivery_api
    image: delivery_api
    restart: always
    environment:
      - ConnectionString=Server=delivery_db;Port=5432;Database=postgres;User Id=postgres;Password=admin
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - 81:80
    networks:
      - project-network
    depends_on:
      - db
    command: ["./wait-for-postgres.sh", "admin", "delivery_db"]

networks:
  project-network:
    external: true

