FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

ENV ConnectionString "Server=delivery_db;Port=5433;Database=postgres;User Id=postgres;Password=admin"
ENV ASPNETCORE_ENVIRONMENT "Release"


EXPOSE 80
# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "DeliveryPoints.dll"]